openapi: 3.0.3
info:
  title: Todo Service
  description: Service that manage todo.
  version: "1.0"
servers:
- url: http://localhost:8088
paths:
  /hello/{name}:
    get:
      tags:
      - todo
      summary: hello todo
      operationId: todo#hello
      parameters:
      - name: name
        in: path
        description: Name
        required: true
        schema:
          type: string
          description: Name
          example: Qui ea aut labore vel est.
        example: Repellendus cum pariatur.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: string
                example: Quo at aut vero dolorem.
              example: Dolor impedit officiis et repellat.
  /todo:
    post:
      tags:
      - todo
      summary: create todo
      operationId: todo#create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRequestBody'
            example:
              title: Corrupti odit enim nisi itaque eveniet.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: string
                example: Ex voluptatibus autem.
              example: Exercitationem recusandae natus molestiae mollitia autem aliquid.
  /todo/{id}:
    get:
      tags:
      - todo
      summary: show todo
      operationId: todo#show
      parameters:
      - name: id
        in: path
        description: ID
        required: true
        schema:
          type: integer
          description: ID
          example: 3186684057996810352
          format: int64
        example: 7641188071616973852
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
              example:
                id: 4180047692902679739
                is_done: false
                title: Enim cupiditate eaque.
    post:
      tags:
      - todo
      summary: update todo
      operationId: todo#update
      parameters:
      - name: id
        in: path
        description: ID
        required: true
        schema:
          type: integer
          description: ID
          example: 238078235876912336
          format: int64
        example: 4444182031962655905
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRequestBody'
            example:
              is_done: false
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: string
                example: Omnis molestiae similique.
              example: Sint velit.
components:
  schemas:
    CreateRequestBody:
      type: object
      properties:
        title:
          type: string
          description: Title
          example: Provident voluptates natus.
      example:
        title: Quam voluptatem sit voluptatem officia est.
      required:
      - title
    Todo:
      type: object
      properties:
        id:
          type: integer
          description: ID
          example: 657734008950643814
          format: int64
        is_done:
          type: boolean
          description: IsDone
          example: false
        title:
          type: string
          description: Title
          example: Est error magni fugit ipsam itaque.
      example:
        id: 1569166430780697639
        is_done: false
        title: Voluptas vitae ex quas.
    UpdateRequestBody:
      type: object
      properties:
        is_done:
          type: boolean
          description: IsDone
          example: false
      example:
        is_done: true
      required:
      - is_done
tags:
- name: todo
  description: Service that manage todo.
